import Head from "next/head";
import React from "react";
import AgendaLayout from "../components/dashboard/agenda/AgendaLayout";
import Calendar from "../components/dashboard/agenda/calendar/Calendar";

function Agenda() {
	return (
		<div style={{ display: "flex", justifyContent: "center" }}>
			<Head>
				<title>{"Cat'Monitoring - Agenda"}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/icon.png" />
			</Head>
			<AgendaLayout />
		</div>
	);
}

export default Agenda;
