import Head from "next/head";
import React from "react";

function Agenda() {
	return (
		<div style={{ display: "flex", justifyContent: "center" }}>
			<Head>
				<title>{"Cat'Monitoring - Agenda"}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/icon.png" />
			</Head>
			{/* <AgendaLayout /> */}
			{/* Travaux en cours */}
		</div>
	);
}

export default Agenda;
