import Head from "next/head";
import React from "react";

function Agenda() {
	return (
		<div>
			<Head>
				<title>{"Cat'Monitoring - Agenda"}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/icon.png" />
			</Head>
			<span>agenda</span>
		</div>
	);
}

export default Agenda;
