import Head from "next/head";
import HomeLayout from "../components/dashboard/home/HomeLayout";

function Home() {
	return (
		<div style={{ display: "flex", justifyContent: "center" }}>
			<Head>
				<title>{"Cat'Monitoring - Accueil"}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/icon.png" />
			</Head>
			<HomeLayout />
		</div>
	);
}

export default Home;
