import React from "react";
import Head from "next/head";
import NutritionLayout from "../components/dashboard/nutrition/NutritionLayout";

function Regime() {
	return (
		<div style={{ display: "flex", justifyContent: "center" }}>
			<Head>
				<title>{"Cat'Monitoring - Régime"}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/icon.png" />
			</Head>
			<NutritionLayout />
		</div>
	);
}

export default Regime;
